import { IRMPermissions } from '@app/models';

export const AdminPermissions = [
  IRMPermissions.InstallationEquipment,
  IRMPermissions.InstallationEquipmentDescription,
  IRMPermissions.DAonAssignment,
  IRMPermissions.DAinStore,
  IRMPermissions.DisposalEquipment,
  IRMPermissions.GlobalSearch,
  IRMPermissions.AvailableQuotas,
  IRMPermissions.QuotaReservation,
  IRMPermissions.MutualSettlements,
  IRMPermissions.DirectoryMVZ,
  IRMPermissions.AllDirectories,
  IRMPermissions.DirectoryIRM,
  IRMPermissions.UsersIRM,
  IRMPermissions.ServicePageIRM,
  IRMPermissions.Reports,
  IRMPermissions.InformationMaterials,
  IRMPermissions.RegisterRequests,
  IRMPermissions.DirectoryServiceCompany,
  IRMPermissions.HandbookMasters,
  IRMPermissions.Recycling,
  IRMPermissions.RecyclingMain,
  IRMPermissions.RecyclingService,
  IRMPermissions.RecyclingSettlementsWithLogisticians,
  IRMPermissions.RecyclingDictionaries,
  IRMPermissions.RecyclingUsers,
  IRMPermissions.RecyclingServicePage
];
